hidden_size: 64
conv_name: GCN
n_layers: 1
attention: false
no_block_embedding: false
e3_dim: 30
tar_dim: 30
protac_dim: 167
feature: true
device: cpu
mode: Train
epoch_pre: 30
epoch: 2000
lr: 0.0001
lr_l: 0.001
batch_size: 4
train_rate: 0.8
class_num: 2
seed: 111
dataset_type: name
dataset_root: ../data/PROTAC
save_dir: runs_classification
run_name: classification_baseline
select_pocket_war: 10
select_pocket_e3: 10
k_neighbors: 9
w_consistent: 0.0
w_ent: 0.0
margin: 0.4
num_k: 1000
T: 0.5
start_epoch: 0
end_epoch: 20
